server:
  port: 50000 # 端口
spring:
  application:
    name: min-mall # 项目名称
  profiles:
    active: dev # 当前开发环境
  datasource:
    type: com.zaxxer.hikari.HikariDataSource # 指定数据库连接池（默认会检查到此连接池）
    hikari:
      auto-commit: true # 自动提交（默认true）
      connection-timeout: 30000 # 连接超时时间（单位：毫秒）（默认值：30秒）
      idle-timeout: 600000 # 连接在池中闲置的最长时间（单位：毫秒）（默认值：10分钟）
      max-lifetime: 1200000 # 池中连接的最长生命周期（单位：毫秒）（默认值：30分钟）
      maximum-pool-size: 10 # 池达到的最大大小，包括空闲和使用中的连接（默认值：10）
      minimum-idle: 5 # 池中维护的最小空闲连接数（默认值：与maximum-pool-size相同）
management:
  endpoints:
    web:
      base-path: /ryiuaaey # 指定前置路径
      exposure:
        include: "logfile" # 仅开启日志模块
